/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import com.sun.glass.events.KeyEvent;
import controlador.UsuarioDAO;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Juliano
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txf_nome = new javax.swing.JTextField();
        btn_cadastrar = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        psf_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nome.setText("Nome:");

        jLabel2.setText("Senha:");

        txf_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txf_nomeKeyPressed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        psf_senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psf_senhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lbl_nome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psf_senha))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(psf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_login))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String nome = txf_nome.getText();
        String senha = new String(psf_senha.getPassword());

        Usuario u = new UsuarioDAO().ValidaUsuario(nome, senha);

        if (u != null) {
            if (u.getNome().equals(nome) && u.getSenha().equals(senha)) {
                //JOptionPane.showMessageDialog(null, "Olá, " + nome);
                this.setVisible(false);
                new FormPrincipal(u).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        String nome = txf_nome.getText();
        String senha = new String(psf_senha.getPassword());

        UsuarioDAO uDAO = new UsuarioDAO();
        if (new UsuarioDAO().ValidaUsuario(nome, senha) == null) {
            Usuario u = new Usuario((uDAO.UltimoId() + 1), nome, senha);
            if (uDAO.inserirUsuario(u) == 1) {
                JOptionPane.showMessageDialog(null, "Usuario criado com sucesso.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuario já existe!");
        }


    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txf_nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_nomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String nome = txf_nome.getText();
            String senha = new String(psf_senha.getPassword());

            Usuario u = new UsuarioDAO().ValidaUsuario(nome, senha);

            if (u != null) {
                if (u.getNome().equals(nome) && u.getSenha().equals(senha)) {
                    //JOptionPane.showMessageDialog(null, "Olá, " + nome);
                    this.setVisible(false);
                    new FormPrincipal(u).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
            }
        }
    }//GEN-LAST:event_txf_nomeKeyPressed

    private void psf_senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psf_senhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String nome = txf_nome.getText();
            String senha = new String(psf_senha.getPassword());

            Usuario u = new UsuarioDAO().ValidaUsuario(nome, senha);

            if (u != null) {
                if (u.getNome().equals(nome) && u.getSenha().equals(senha)) {
                    //JOptionPane.showMessageDialog(null, "Olá, " + nome);
                    this.setVisible(false);
                    new FormPrincipal(u).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
            }
        }
    }//GEN-LAST:event_psf_senhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JPasswordField psf_senha;
    private javax.swing.JTextField txf_nome;
    // End of variables declaration//GEN-END:variables
}
